version: '3.7'
services:
    postgres:
        image: postgres:13.6-alpine
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - '5438:5432'
        volumes:
          - ./data:/var/lib/postgresql/data
          - ./backup:/var/lib/postgresql/backup