Vagrant.configure("2") do |config|
    config.vm.define "pcs-devsys-diplom" do |subconfig|
      subconfig.vm.box = "bento/ubuntu-20.04"
      subconfig.vm.hostname = "pcs-devsys-diplom"
      subconfig.vm.network :public_network, bridge: "enp8s0", ip: "192.168.100.200"
    end
end